version: "3.8"
services:
  java:
    build: ./persons
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/carinspect
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres_db
  node:
    build: ./portfolios
    ports:
      - "3333:3333"
    depends_on:
      - mongo_db
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carinspect
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
volumes:
  postgres_data:
  mongo_data:
