version: "3.8"
services:
  portfolios:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
