version: "3.8"
services:
  surveys:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - data:/data/db
volumes:
  data:
