version: "3.8"
services:
  java-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carinspect
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carinspect
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
